# Initial Workbook

## Libary Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import import_ipynb

from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report, balanced_accuracy_score
from dotenv import load_dotenv


## Exploratory Data Analysis (EDA)

In [2]:
from spark.preprocessor import preprocessor

In [3]:
X_train, X_test, y_train, y_test = preprocessor("/Users/sebastian.zilles/code/marzecovaa/spark/processed_data/merged_dfq.csv")

✅ Transformer saved at: ./model_registry/transformer_20250905-144544.joblib


/Users/sebastian.zilles/.pyenv/versions/3.10.6/envs/spark/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


In [4]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5860 stored elements and shape (375, 413)>

In [5]:
base_model_xgb = XGBClassifier()
base_model_xgb.fit(X_train,y_train)

y_pred = base_model_xgb.predict(X_test)


# ✅ Metrics
print("Balanced Accuracy:", balanced_accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Balanced Accuracy: 0.6252140974967062

Confusion Matrix:
 [[11  2  3]
 [ 1 51  3]
 [ 3 14  6]]

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.69      0.71        16
           1       0.76      0.93      0.84        55
           2       0.50      0.26      0.34        23

    accuracy                           0.72        94
   macro avg       0.66      0.63      0.63        94
weighted avg       0.69      0.72      0.69        94

