# Initial Workbook

## Libary Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import import_ipynb

from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report, balanced_accuracy_score


## Exploratory Data Analysis (EDA)

In [11]:
from spark.preprocessor import preprocessor

In [12]:
X_train, X_test, y_train, y_test = preprocessor("~/code/marzecovaa/spark/processed_data/merged_dfq_v2.csv")

In [ ]:
base_model_xgb = XGBClassifier()
base_model_xgb.fit(X_train,y_train)

y_pred = base_model_xgb.predict(X_test)


# ✅ Metrics
print("Balanced Accuracy:", balanced_accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


🔹 Balanced Accuracy: 0.6236166007905138

🔹 Confusion Matrix:
 [[10  3  3]
 [ 3 47  5]
 [ 3 11  9]]

🔹 Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.62      0.62        16
           1       0.77      0.85      0.81        55
           2       0.53      0.39      0.45        23

    accuracy                           0.70        94
   macro avg       0.64      0.62      0.63        94
weighted avg       0.69      0.70      0.69        94

